# Pandas

[Pandas的功能](http://pandas.pydata.org)     
Pandas是一个强大的分析结构化数据的工具集，提供了高级数据结构和数据操作工具，它是使Python成为强大而高效的数据处理环境的重要因素之一。

Numpy能够帮助我们处理数值，但是pandas除了处理数值之外(基于numpy)，还能够帮助我们处理其他类型的数据，提供了大量能够快速便捷地处理数据的函数和方法。



### Pandas的数据结构
 - Series，一维，带标签的数组，List中的元素可以是不同的数据类型，Series中则只允许存储相同的数据类型。    
 - DataFrame，二维，Series容器   
 - Panel，三维（扩展）   

####  Series
Series是一种类似于一维数组的对象，能够保存任何数据类型（整数，字符串，浮点数，Python对象等）。   
由一组数据以及一组与之对应的索引组成，索引(index)在左，数据(values)在右。

In [139]:
import pandas as pd
ser_obj = pd.Series(range(10, 20))
print(ser_obj.head(5))
print(type(ser_obj))
print( '\n'*1 )
# 获取数据
print(ser_obj.values)
# 获取索引
print(ser_obj.index)
#通过索引获取数据
print(ser_obj[8])

0    10
1    11
2    12
3    13
4    14
dtype: int64
<class 'pandas.core.series.Series'>


[10 11 12 13 14 15 16 17 18 19]
RangeIndex(start=0, stop=10, step=1)
18


In [140]:
# 通过dict构建Series
year_data = {2001: 17.8, 2002: 20.1, 2003: 16.5}
ser_obj2 = pd.Series(year_data)
print(ser_obj2.head())
print(ser_obj2.index)
# 对象名：ser_obj2.name   
#对象索引名：ser_obj2.index.name
ser_obj2.name = 'temp'
ser_obj2.index.name = 'year'

2001    17.8
2002    20.1
2003    16.5
dtype: float64
Int64Index([2001, 2002, 2003], dtype='int64')


#### DataFrame
DataFrame是一个二维标记数据结构，类似多维数组/表格数据，它含有一组有序的列，每列可以是不同类型的值。     
DataFrame既有行索引也有列索引，它可以被看做是由Series组成的字典（共用同一个索引），数据是以二维结构存放的。

     
 
  


In [59]:
import numpy as np
# 通过ndarray构建DataFrame
array = np.random.randn(5,4)
print(array)
print( '\n'*1 )
df_obj = pd.DataFrame(array)
print(df_obj.head())

[[-0.2685059  -0.5264529   0.79993037 -0.45251731]
 [ 0.18667391  0.05632258  0.95593401  0.22231752]
 [-0.26587893 -1.17773156 -0.26075826  0.0636375 ]
 [-0.72054506  1.38708311 -0.94495735 -0.41909144]
 [ 0.12487893 -0.44650323 -0.1358003  -0.30068824]]


          0         1         2         3
0 -0.268506 -0.526453  0.799930 -0.452517
1  0.186674  0.056323  0.955934  0.222318
2 -0.265879 -1.177732 -0.260758  0.063637
3 -0.720545  1.387083 -0.944957 -0.419091
4  0.124879 -0.446503 -0.135800 -0.300688


In [61]:
# 通过dict构建DataFrame
dict_data = {'A': 1, 
             'B': pd.Timestamp('20170426'),
             'C': pd.Series(1, index=list(range(4)),dtype='float32'),
             'D': np.array([3] * 4,dtype='int32'),
             'E': ["Python","Java","C++","C"],
             'F': 'ITCast' }
df_obj2 = pd.DataFrame(dict_data)
print(df_obj2)
print( '\n'*1 )
# 通过列索引获取列数据
print(df_obj2['A'])
print(type(df_obj2['A']))
print( '\n'*1 )
# 增加列
df_obj2['G'] = df_obj2['D'] +  5
print(df_obj2.head())
# 删除列
del(df_obj2['G'] )
print(df_obj2.head())

   A          B    C  D       E       F
0  1 2017-04-26  1.0  3  Python  ITCast
1  1 2017-04-26  1.0  3    Java  ITCast
2  1 2017-04-26  1.0  3     C++  ITCast
3  1 2017-04-26  1.0  3       C  ITCast


0    1
1    1
2    1
3    1
Name: A, dtype: int64
<class 'pandas.core.series.Series'>


   A          B    C  D       E       F  G
0  1 2017-04-26  1.0  3  Python  ITCast  8
1  1 2017-04-26  1.0  3    Java  ITCast  8
2  1 2017-04-26  1.0  3     C++  ITCast  8
3  1 2017-04-26  1.0  3       C  ITCast  8
   A          B    C  D       E       F
0  1 2017-04-26  1.0  3  Python  ITCast
1  1 2017-04-26  1.0  3    Java  ITCast
2  1 2017-04-26  1.0  3     C++  ITCast
3  1 2017-04-26  1.0  3       C  ITCast


### Pandas的索引操作

In [17]:
# 索引对象不可变
df_obj2.index[0] = 2

TypeError: Index does not support mutable operations

In [62]:
#Series索引
ser_obj = pd.Series(range(5), index = ['a', 'b', 'c', 'd', 'e'])
print(ser_obj.head())
# 行索引
print(ser_obj['b'])
print(ser_obj[2])
# 切片索引
print(ser_obj[1:3])
print(ser_obj['b':'d'])
# 不连续索引
print(ser_obj[[0, 2, 4]])

a    0
b    1
c    2
d    3
e    4
dtype: int64
1
2
b    1
c    2
dtype: int64
b    1
c    2
d    3
dtype: int64
a    0
c    2
e    4
dtype: int64


In [17]:
#DataFrame索引
import numpy as np
#columns指定列索引名
df_obj = pd.DataFrame(np.random.randn(5,4), columns = ['a', 'b', 'c', 'd']) 
print(df_obj.head())
# 列索引
print(df_obj['a']) # 返回Series类型
print(df_obj[['a']]) # 返回DataFrame类型
print(type(df_obj[['a']])) 
# 不连续索引
print(df_obj[['a','c']])
print(type(df_obj[['a','c']]))

          a         b         c         d
0 -1.140965  0.244823 -0.768640 -0.858732
1  0.071233 -0.035887  0.854415  0.323309
2 -0.377314 -0.841886 -0.218971 -1.219190
3 -2.003118  0.548587  0.872923 -0.446656
4 -0.493338 -0.727477  0.645850 -0.656872
0   -1.140965
1    0.071233
2   -0.377314
3   -2.003118
4   -0.493338
Name: a, dtype: float64
          a
0 -1.140965
1  0.071233
2 -0.377314
3 -2.003118
4 -0.493338
<class 'pandas.core.frame.DataFrame'>
          a         c
0 -1.140965 -0.768640
1  0.071233  0.854415
2 -0.377314 -0.218971
3 -2.003118  0.872923
4 -0.493338  0.645850
<class 'pandas.core.frame.DataFrame'>


### Pandas的数据计算

In [102]:
import numpy as np
import pandas as pd
df_obj = pd.DataFrame(np.random.randn(5,4), columns = ['a', 'b', 'c', 'd'])
print(df_obj)

          a         b         c         d
0 -0.128458 -0.239049  1.268771 -0.483132
1  0.610187  0.011347 -0.220402 -0.725317
2  0.383537 -1.509982 -0.945710  1.057704
3 -0.240553 -0.774224  0.778547 -1.486289
4 -0.372635  0.550255 -0.226011 -1.246501


In [106]:
#常用的计算axis=0 按列统计，axis=1按行统计
print(df_obj.sum())
print(df_obj.count())
print( '\n'*1 )
#describe 产生多个统计数据
print(df_obj.describe())

a    0.252078
b   -1.961653
c    0.655194
d   -2.883534
dtype: float64
a    5
b    5
c    5
d    5
dtype: int64


              a         b         c         d
count  5.000000  5.000000  5.000000  5.000000
mean   0.050416 -0.392331  0.131039 -0.576707
std    0.424248  0.785797  0.883754  0.997259
min   -0.372635 -1.509982 -0.945710 -1.486289
25%   -0.240553 -0.774224 -0.226011 -1.246501
50%   -0.128458 -0.239049 -0.220402 -0.725317
75%    0.383537  0.011347  0.778547 -0.483132
max    0.610187  0.550255  1.268771  1.057704


In [141]:
#处理缺失数据
df_data = pd.DataFrame([np.random.randn(3), [1., 2., np.nan],
                       [np.nan, 4., np.nan], [1., 2., 3.]])
print(df_data.head())
# isnull
print(df_data.isnull())
# dropna根据axis轴方向，丢弃包含NaN的行或列
print(df_data.dropna())
print(df_data.dropna(axis=1))#指定行列
# fillna填充缺失数据
print(df_data.fillna(-99.))

          0         1        2
0  1.650403 -0.204041  0.99448
1  1.000000  2.000000      NaN
2       NaN  4.000000      NaN
3  1.000000  2.000000  3.00000
       0      1      2
0  False  False  False
1  False  False   True
2   True  False   True
3  False  False  False
          0         1        2
0  1.650403 -0.204041  0.99448
3  1.000000  2.000000  3.00000
          1
0 -0.204041
1  2.000000
2  4.000000
3  2.000000
           0         1         2
0   1.650403 -0.204041   0.99448
1   1.000000  2.000000 -99.00000
2 -99.000000  4.000000 -99.00000
3   1.000000  2.000000   3.00000


### Pandas的分组聚合

In [131]:
import pandas as pd
import numpy as np

dict_obj = {'key1' : ['a', 'b', 'a', 'b', 
                      'a', 'b', 'a', 'a'],
            'key2' : ['one', 'one', 'two', 'three',
                      'two', 'two', 'one', 'three'],
            'data1': np.random.randn(8),
            'data2': np.random.randn(8)}
df_obj = pd.DataFrame(dict_obj)
print(df_obj)

  key1   key2     data1     data2
0    a    one  0.800854  1.254107
1    b    one -0.359615  1.339783
2    a    two  0.663312 -0.952899
3    b  three  2.199351 -1.179059
4    a    two -0.182035 -0.007730
5    b    two -0.003307 -0.397958
6    a    one  0.508948 -1.067804
7    a  three  0.067674  1.520381


In [132]:
# 分组运算
# 单层分组，根据key1
grouped1 = df_obj.groupby('key1')
for group_name, group_data in grouped1:
    print(group_name)
    print(group_data)
print( '\n'*1 )
# 多层分组，根据data1
grouped2 = df_obj['data1'].groupby(df_obj['key1'])
for group_name, group_data in grouped2:
    print(group_name)
    print(group_data)

a
  key1   key2     data1     data2
0    a    one  0.800854  1.254107
2    a    two  0.663312 -0.952899
4    a    two -0.182035 -0.007730
6    a    one  0.508948 -1.067804
7    a  three  0.067674  1.520381
b
  key1   key2     data1     data2
1    b    one -0.359615  1.339783
3    b  three  2.199351 -1.179059
5    b    two -0.003307 -0.397958


a
0    0.800854
2    0.663312
4   -0.182035
6    0.508948
7    0.067674
Name: data1, dtype: float64
b
1   -0.359615
3    2.199351
5   -0.003307
Name: data1, dtype: float64


In [135]:
#聚合 (aggregation)常用于对分组后的数据进行计算
print(df_obj.groupby('key1').sum())
print(df_obj.groupby('key1').mean())

         data1     data2
key1                    
a     1.858752  0.746056
b     1.836428 -0.237235
         data1     data2
key1                    
a     0.371750  0.149211
b     0.612143 -0.079078


In [134]:
# 自定义聚合函数grouped.agg(func)
def peak_range(df):
    """
        返回数值范围
    """
    #print type(df) #参数为索引所对应的记录
    return df.max() - df.min()

print(df_obj.groupby('key1').agg(peak_range))
print(df_obj.groupby('key1').agg(lambda df : df.max() - df.min()))

         data1     data2
key1                    
a     0.982890  2.588186
b     2.558966  2.518842
         data1     data2
key1                    
a     0.982890  2.588186
b     2.558966  2.518842


### Pandas的数值重构

In [136]:
import pandas as pd
import numpy as np

df_obj1 = pd.DataFrame({'key': ['b', 'a', 'a', 'c', 'a', 'a', 'a'],
                        'data1' : np.random.randint(0,10,7)})
df_obj2 = pd.DataFrame({'key': ['a', 'b', 'c'],
                        'data2' : np.random.randint(0,10,3)})

print(df_obj1)
print(df_obj2)
# on显示指定“外键”
print(pd.merge(df_obj1, df_obj2, on='key'))

  key  data1
0   b      9
1   a      9
2   a      4
3   c      3
4   a      7
5   a      6
6   a      4
  key  data2
0   a      2
1   b      4
2   c      0
  key  data1  data2
0   b      9      4
1   a      9      2
2   a      4      2
3   a      7      2
4   a      6      2
5   a      4      2
6   c      3      0


In [137]:
#duplicated() 返回布尔型Series表示每行是否为重复行
print(df_obj1.duplicated())
#drop_duplicates() 过滤重复行
print(df_obj1.drop_duplicates())

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool
  key  data1
0   b      9
1   a      9
2   a      4
3   c      3
4   a      7
5   a      6


In [138]:
# 单个值替换单个值
print(df_obj1.replace(3, -100))

# 多个值替换一个值
print(df_obj1.replace([3, 5], -100))

# 多个值替换多个值
print(df_obj1.replace([3, 5], [-100, -200]))

  key  data1
0   b      9
1   a      9
2   a      4
3   c   -100
4   a      7
5   a      6
6   a      4
  key  data1
0   b      9
1   a      9
2   a      4
3   c   -100
4   a      7
5   a      6
6   a      4
  key  data1
0   b      9
1   a      9
2   a      4
3   c   -100
4   a      7
5   a      6
6   a      4
